controllers/AjaxController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Ajax;

class AjaxController extends Controller
{
	public function actionSendmail() {
		if ($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		$result = Ajax::sendMess($request->get('ids'), $request->get('summ'), $request->get('dateto'));
		
		echo $result;
		die;
	}
	
	public function actionSms() {
		if ($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		
		$phone = $request->get('sitelogin', false);
		echo Ajax::PostSendSMS(urldecode($phone));
		
		die;
	}
	
	public function actionPaykeeper() {
		if ($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		$session = Yii::$app->session;
		
		$orderid = $request->get('inpids', '');
		$order_sum = $request->get('inpsumm', 0);
		if($orderid == '') $orderid = 'все текущие';
		
		$data = Ajax::PostUserInfo();
		$client_login = $data['data']->UserInfo->FIO;
		
		$phone = trim($session->get('userphone'));
		
// 		var_dump($client_login,$orderid,$order_sum,$phone); die;
		
		$payment_parameters = http_build_query(array(
			"clientid" => $client_login,
			"orderid" => $orderid,
			"sum" => $order_sum,
			"client_phone" => $phone
			));
		$options = array(
			"http"=>array(
			"method"=>"POST",
			"header"=>
			"Content-type: application/x-www-form-urlencoded",
			"content"=>$payment_parameters
		   ));
		$context = stream_context_create($options);
		
		echo file_get_contents("https://demo.paykeeper.ru/order/inline/",FALSE, $context);
		die;
	}
	
	private function checkNoSession() {
		$session = Yii::$app->session;
		if ($session->has('registeruser') && $session->get('registeruser') == 'y') return false;
		return true;
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Ajax;

class SiteController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		$request = Yii::$app->request;
		$session = Yii::$app->session;
		$sitelogin = $request->post('login', '');
		$password = $request->post('password', '');
		$try_sess = $pass = 0;
		$vf = $error = $pass = '';
		
		$now = date('d-m-Y H:i:s');
		 
		if ($sitelogin != '') {
			$vf = Ajax::PostUserInfoVerify( $sitelogin );
			if( $vf->Error != '' ) $error =  $vf->Error . '<br />' . $vf->Description;
			else {
				$try_sess = 5;
				$pass = rand(10000, 99999);
				$session->destroy();
				$session->open();
				$session->set('userphone', $sitelogin);
				$session->set('smscode', $pass);
				$session->set('try', $try_sess);

				$user = Ajax::getUser();
				if($user === false) {
					$ex = Yii::$app->db->createCommand()->insert('y_users', [
						'phone' => $session->get('userphone'),
						'enter' => $try_sess,
						'ip' => Yii::$app->request->userIP,
						'data' => $now,
						'blocked' => 0,
					])->execute();
					$session->set('lastenter', $now);
				} else {
					$session->set('lastenter', $user['data']);
					Yii::$app->db->createCommand("UPDATE y_users SET blocked=0, data='" . $now . "', enter=" . $try_sess . ", ip='" . Yii::$app->request->userIP . "' WHERE id=" . $user['id'])->execute();
				}
				// echo '<pre>';var_dump($user);echo '</pre>';
			}
			
		} else if ($password != '' && $session->has('smscode') && $session->get('smscode') == $password) {
			if (!$session->isActive) $session->open();
			$session->set('registeruser', 'y');
			
		} else if ($password != '' && $session->has('try') && $session->get('try') > 0) {
			$try_sess = $session->get('try');
			$try_sess--;
			$session->set('try', $try_sess );
			$pass = $session->get('smscode');
			$user = Ajax::getUser();
			Yii::$app->db->createCommand("UPDATE y_users SET data='" . $now . "', blocked=0, enter=" . $try_sess . ", ip='" . Yii::$app->request->userIP . "' WHERE id=" . $user['id'])->execute();
		}
		
		if( !$this->checkNoSession() ) {
			$user = Ajax::getUser();
			Yii::$app->db->createCommand("UPDATE y_users SET data='" . $now . "', blocked=1, ip='" . Yii::$app->request->userIP . "' WHERE id=" . $user['id'])->execute();
			return $this->redirect('/site/my-loans');
		} else
			return $this->render('index', array('try_sess' => $try_sess, 'pass' => $pass, 'error' => $error));
	}
	
	public function actionExit() {
		$session = Yii::$app->session;
		$session->destroy();
		$this->redirect('/');
	}
	
	public function actionUserInfo() {
		if ($this->checkNoSession()) return $this->redirect('/');
		$data = Ajax::PostUserInfo();
		return $this->render('user-info', $data);
	}
	
	public function actionLoanHistory() {
		if ($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		$filter = $request->post('sort', false);
		$data = Ajax::PostInfoZalogodatel($filter);
		return $this->render('loan-history', $data);
	}
	
	public function actionMyLoans() {
		if($this->checkNoSession()) return $this->redirect('/');
		
		$data = Ajax::PostInfoZalogodatel(false);
		return $this->render('my-loans', $data);
	}
	
	public function actionInterestPayment() {
		if($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		$ids = $request->get('ids', false);
		$data = Ajax::PostInfoZalogodatelPayment($ids);
		return $this->render('interest-payment', $data);
	}
	
	public function actionOrderRedemption() {
		if($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		$ids = $request->get('ids', false);
		$date = $request->get('date', '');
		$data = Ajax::PostInfoZalogodatelPayment($ids, $date);
		return $this->render('order-redemption', $data);
	}
	
	public function actionInterestCalculator() {
		if($this->checkNoSession()) return $this->redirect('/');
		$session = Yii::$app->session;
		
		// echo '<pre>';var_dump($ex, $posts);echo '</pre>';
		
		$request = Yii::$app->request;
		$ids = $request->get('ids', false);
		$date = $request->get('date', '');
		$data = Ajax::PostInfoZalogodatelPayment($ids, $date);
		return $this->render('interest-calculator', $data);
	}
	
	public function actionLoanItem() {
		if($this->checkNoSession()) return $this->redirect('/');
		
		$request = Yii::$app->request;
		$id = $request->get('id', false);
		$data = Ajax::PostInfoItem($id);
		return $this->render('loan-item', $data);
	}
	
	public function actionPersonalArea() {
		if($this->checkNoSession()) return $this->redirect('/');
		
		$data = Ajax::PostInfoZalogodatel(false);
		return $this->render('personal-area', $data);
	}
	
	public function actionPromotions() {
		if($this->checkNoSession()) return $this->redirect('/');
		
		$data = Ajax::PostUserInfo();
		return $this->render('promotions', $data);
	}
	/**
	 * Login action.
	 *
	 * @return Response|string
	 */
	public function actionLogin()
	{
		if($this->checkNoSession()) return $this->redirect('/');
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		}

		$model->password = '';
		return $this->render('login', [
			'model' => $model,
		]);
	}

	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		if($this->checkNoSession()) return $this->redirect('/');
		
		Yii::$app->user->logout();

		return $this->goHome();
	}

	/**
	 * Displays contact page.
	 *
	 * @return Response|string
	 */
	public function actionContact()
	{
		if($this->checkNoSession()) return $this->redirect('/');
		
		$model = new ContactForm();
		if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
			Yii::$app->session->setFlash('contactFormSubmitted');

			return $this->refresh();
		}
		return $this->render('contact', [
			'model' => $model,
		]);
	}

	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout()
	{
		if($this->checkNoSession()) return $this->redirect('/');
		
		$url = 'http://85.30.228.34:7780/Test/hs/LK_Zalogodatel/PostUserInfo';
		$login = 'lk1';
		$password = '789456';
		$header = array(
				'Content-Type: application/json'
			);
		$payloadName = array(
			'Tel' => '+7 (451) 315-44-56',
			"Date" => "2021-02-05T11:59:51"
			);
		$postfields = json_encode($payloadName);
		
		$ch = curl_init();
		
		curl_setopt($ch, CURLOPT_URL, $url );
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
		curl_setopt($ch, CURLOPT_USERPWD, "$login:$password");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $postfields );
		curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
		curl_setopt($ch, CURLOPT_TIMEOUT, 20);
		
		$response = curl_exec($ch);
		curl_close($ch);
		$data['req'] = json_decode($response);
		
		return $this->render('about', $data);
	}
	
	private function checkNoSession() {
		$session = Yii::$app->session;
		if ($session->has('registeruser') && $session->get('registeruser') == 'y') return false;
		return true;
	}
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

<pre>
<?php var_dump($req); ?>    
    
</pre>
    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
          <div class="col-lg-6">
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'вход';
// $this->registerJs('
//     $("#send-sms").on("click", function () {
//       var number = $("#login").val();
//             $.ajax({
//                 url: "' . Url::toRoute(['ajax/sms']) . '",
//                 dataType: "html",
// 		        type: "get",
//                 data: "sitelogin="+encodeURIComponent(number),
//                 success: function(data){
//                     $("#entercontent").html(data);
//                     console.log(data);
//                 },
//                 error: function () {
//                     $("#message").html("ERROR");
//                 }
//             });
//         });
//     ');
?>
          <div class="col-lg-6">
            <div class="login-form">
              <div class="login-form__box">
                <div class="login-form__header">
                  <div class="login-form__title">Личный кабинет</div>
                </div>
                <div class="login-form__body">
                  <div class="login-form__links"><a href="#!">Вход</a><!--a href="#!">Стать клиентом </a--></div>
                  <div class="login-form__info">Введите номер телефона в заданном формате, на который придет СМС для авторизации</div>
                  <?= Html::beginForm(['/'], 'post', ['autocomplete' => 'off']); ?>
                    <div id="message">
                        <?php if ($error != '' ) echo ( $error); ?>
                    </div>
                    <div id="entercontent">
                    <?php 
                    if ($try_sess > 0) {
                        echo '<div>отправили СМС с кодом: ' . $pass . '<br />Попыток входа ' . $try_sess . '</div>'; 
                        $inpdata = array('class' => 'form-control form-control-lg', 'id' => 'password', 'autocomplete' => 'off', 'placeholder' => 'Введите код из СМС');
                        $btndata = array('class' => 'btn btn-danger btn-lg btn-block','id' => 'btnsubmit' );
                    ?>
                    
                    <div class="form-group">
                        <label for="password">Пароль из СМС</label>
                        <?= Html::input('password', 'password', '', $inpdata ) ?>
                    </div>
                    <div class="form-group">
                        <?= Html::input('submit', 'enter', 'Войти', $btndata) ?>
                    </div>
                    
                    <?php } else { 
                    ?>
                    <br />
                        (256) 456-46-54<br />
                        (135) 145-46-46<br />
                        (554) 645-64-64<br />
                        (906) 660-26-95<br />
                        (125) 314-65-46<br />
                    <?php
                        $inpdata = array('class' => 'form-control form-control-lg', 'id' => 'login', 'autocomplete' => 'off', 'placeholder' => 'ваш телефон');
                        $btndata = array('class' => 'btn btn-danger btn-lg btn-block','id' => 'btnsubmit');
                    ?>
                    
                    <div class="form-group"><label for="login">Телефон</label>
                    <?= Html::input('text', 'login', '', $inpdata) ?>
                    </div>
                    <div class="form-group">
                        <?= Html::input('submit', 'send-sms', 'Получить код по СМС', $btndata) ?>
                    </div>
                    
                    <?php } ?>
                    </div>
                  <?= Html::endForm() ?>
              </div>
            </div>
          </div>
          <div class="col-lg-3"></div>

views/site/order-redemption.php
<?php
use yii\helpers\Url;
use app\models\Settings;

$request = Yii::$app->request;
$ids = $request->get('ids', '');

$this->title = 'Текущие займы по отделению';
$this->registerJs('
	$(".js-date-go").datepicker({
		position: "bottom right",
		autoClose: true,
		onSelect: function(formattedDate, date, inst) {
			document.location.href="/site/order-redemption?date=" + formattedDate + "' . $ids . '";
		}
	});
	function checkSummProc(officeid) {
		var summ = 0,
		zalog = 0,
		zalogAll = 0,
		all;
		var ids = [];
		$("#office_"+ officeid +" input:checkbox:checked").each(function(){
			summ = summ+parseInt($(this).val());
			ids.push( $(this).attr("data-ids") );
			zalog += parseInt($(this).parent().parent().parent().parent().attr("data-price"));
		});
		$(".loan-item-small").each(function(){
			zalogAll += parseInt($(this).attr("data-price"));
		});
		
		if (summ == 0) {
			summ = parseInt($("#office_"+ officeid +" #summProc").attr("data-val"));
			all = (summ + zalogAll);
			$("#office_"+ officeid +" #countProc").text("все");
			$("#summZaim").text(zalogAll + " P");
		} else {
			all = (summ + zalog);
			$("#office_"+ officeid +" #countProc").text(ids.length + " шт");
			$("#summZaim").text(zalog + " P");
		}
		$("#office_"+ officeid +" #summProc").text(summ + " Р").parent().attr("data-ids", ids.join(","));
		$("#summAll, #summProcModal").text(all +  " P");
		$("#inpids").val(ids.join(","));
		$("#inpsumm").val(all);
	}
	function startIntrPay() {
		$(".department").each(function(){
			checkSummProc($(this).attr("data-office"));
		});
	}
	$(document).ready(function() {
		startIntrPay();
		$("input[name=\'items[]\']").on("change", function () {
			checkSummProc($(this).attr("data-office"));
		});
		$("#checkall").on("change", function() {
			if ( $(this).is(":checked") ) {
				$("input[name=\'items[]\']").attr("checked", "checked");
			} else {
				$("input[name=\'items[]\']").removeAttr("checked");
			}
			startIntrPay();
		});
		$("#sendpos").on("click", function() {
			var ids = $("#inpids").val();
			var summ = $("#inpsumm").val();
			var dateto = $("#dateto").val();
			$.ajax({
				url: "' . Url::toRoute(['/ajax/sendmail']) . '",
				dataType: "html",
				type: "get",
				data: "ids="+encodeURIComponent(ids)+"&summ="+summ+"&dateto="+dateto,
				success: function(data){
					//$("#sendmailresult, #sendpos").html(data);
					$("#sendpos").html(data);
					$("#sendpos").addClass("disabled").removeAttr("id");
					//console.log(data);
				},
				error: function () {
					$("#sendmailresult").html("Ошибка отправки");
				}
			});
		});
	});
');
	if ($Error != '') {
		echo $Error . '<br />' . $Description;
	} else {
	$count = count($data)-1;
	$part = '';
	$i = $summoffice = $summofficeall = $office = $summZalogCheck = $summZalog = 0;

?>
		<div class="col-lg-9">
			<div class="page-title">Заказать для выкупа на</div>
				<div class="block-select-date">
					<div class="block-select-date__box">
						<input class="js-date-go" type="text" id="dateto" placeholder="<?= $dateto;?>" value="<?= $dateto;?>" />
						<img src="/assets/img/icons/icon-calendar.png" alt="icon-calendar" />
					</div>
				</div>
			<div>
				<div class="checkbox-custome path">
					<label><input type="checkbox" id="checkall" />
					<svg viewBox="0 0 21 21">
						<path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
						</svg><span>Выбрать все</span></label>
				</div>
			</div>
<?php
	foreach($data as $number=>$zalog) {
		if ($i == 0 ) { ?>
	<div class="department" id="office_<?=$office;?>" data-office="<?=$office;?>">
		<div class="department__title">Текущие займы по отделению «<?= $zalog->OrgNaim; ?>»</div>
		<div class="row">
			<div class="col-sm-8">
				<div class="department__items">
<?php		}
		$w = 0;
		foreach($zalog->Goods as $item) {
			$w++;
			$ch = false;
			$itrmProc = round($zalog->SumProc / $zalog->SumCredit * $item->SumCredit);
			if (in_array( $number . '-' . $w, $checked)) {
				$ch = true;
				$summoffice += $itrmProc;
				$summZalogCheck += $item->SumCredit;
			}
			$summofficeall += $itrmProc;
			$summZalog += $item->SumCredit;
			
			
?>
					<div class="loan-item-small" data-price="<?= $item->SumCredit;?>">
						<div class="loan-item-small__check">
							<div class="checkbox-custome path"><label><input type="checkbox"<?php if($ch) echo 'checked="checked"';?> name="items[]" value="<?= $itrmProc; ?>" data-office="<?=$office;?>" data-ids="<?= $zalog->NumTicket.'-'.$i; ?>" /><svg viewBox="0 0 21 21">
										<path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
									</svg></label></div>
						</div>
						<div class="loan-item-small__media"> <img src="<?= Settings::getPng($item->TypeIzd);?>" alt="<?php echo $item->TypeIzd . ', ' . $item->Proba . ', ' . $item->Ves . ' гр.';?>" /></div>
						<div class="loan-item-small__info"><a class="loan-item-small__number" href="/site/loan-item?id=<?= $number . '-' . $w; ?>">Залоговый<br> билет № <?= $number; ?></a>
							<div class="loan-item-small__desc"><?php echo $item->TypeIzd . ', ' . $item->Proba . '<br />' . $item->Ves . ' гр.';?></div>
						</div>
						<div class="loan-item-small__price"><?= $itrmProc; ?> Р</div>
					</div>
						<?php
		}
		if ($part != $zalog->OrgNaim && $i != $count && $i != 0)  {
			$office++;
										?>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="department__info">
					<p>Общая сумма процентов по отделению «<?= $part; ?>»</p>
					<ul>
						<li><span>Количество, выбранных займов</span><strong id="countProc">1 шт</strong></li>
						<li><span>Итого процентов по займам</span><strong data-val="<?= $summofficeall;?>" id="summProc"><?= $summoffice;?> Р</strong></span>
						<li>
							<div class="checkbox-custome path"><label><input type="checkbox" /><svg viewBox="0 0 21 21">
										<path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
									</svg><span>Оплатить баллами</span></label></div><strong class="green">40</strong>
						</li>
					</ul><button class="btn btn-danger btn-block" data-toggle="modal" data-target="#order-redemption">Оплатить проценты</button>
				</div>
			</div>
		</div>
	</div>
	<div class="department" id="office_<?=$office;?>" data-office="<?=$office;?>">
		<div class="department__title">Текущие займы по отделению «<?= $zalog->OrgNaim; ?>»</div>
		<div class="row">
			<div class="col-sm-8">
				<div class="department__items">
<?php		$summoffice=0;
		} else if ($i == $count) {
			if ($summZalogCheck == 0) $allsumm = $summZalog;
			else $allsumm = $summZalogCheck;
		?>

			</div>
		</div>
		<div class="col-sm-4">
			<div class="department__info">
				<p>Общая сумма процентов по отделению «<?= $zalog->OrgNaim; ?>»</p>
				<ul>
					<li><span>Количество, выбранных займов</span><strong id="countProc"><?= count($checked);?> шт</strong></li>
					<li><span>Общая сумма займа</span><strong data-val="<?= $allsumm;?>" id="summZaim"><?= $allsumm; ?> P</strong></li>
					<li><span>Итого процентов по займам</span><strong data-val="<?= $summofficeall;?>" id="summProc"><?= $summoffice;?> Р</strong></li>
					<li><span>Сумма к выкупу</span><strong data-val="<?= ($allsumm + $summofficeall);?>" id="summAll"><?= ($allsumm + $summofficeall); ?> Р</strong></li>
					</ul>
					<div id="sendmailresult"></div>
					<button class="btn btn-secondary btn-block" id="sendpos">Заказать для выкупа</button>
				</div>
			</div>
		</div>
	</div>
<?php	}

		$i++;
		$part = $zalog->OrgNaim;
	} ?>
					</div>
					
<?php } ?>

views/site/personal-area.php
<?php
$this->title = 'Персональная страница';
?>
          <div class="col-lg-9">
            <div class="personal-area-content">
              <div class="personal-area-item personal-area--user"><a class="personal-area-item__link" href="/user-info.html">
                  <div class="personal-area-item__title">Здравствуйте, Иван Иванов!</div>
                  <div class="personal-area-item__email">ivan@mail.ru</div>
                </a></div>
              <div class="personal-area-item personal-area--payment"><a class="personal-area-item__link" href="/interest-payment.html">
                  <div class="personal-area-item__subtitle">Оплата процентов</div>
                  <div class="personal-area-item__value">341 Р</div>
                </a></div>
              <div class="personal-area-item personal-area--info"><a class="personal-area-item__link" href="#!">
                  <div class="personal-area-item__title">Статус: Участник</div>
                  <div class="personal-area-item__subtitle">Ваши баллы</div>
                  <div class="personal-area-item__value">40</div>
                </a></div>
            </div>
          </div>